#ifndef SENSORSFROMPAYLOAD_H
#define SENSORSFROMPAYLOAD_H

/*
  ID TRANSLATION FROM BLE 
*/
enum sensorData { TIMESTAMP, TROLL, TPITCH, TYAW, 
                 TACCELERATION_X, TACCELERATION_Y, TACCELERATION_Y,
                 TCOMPASS_X, TCOMPASS_Y, TCOMPASS_Z ,
                 TEMPERATURE, THUMIDITY, TALTITUDE };

#endif
